### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorboard'

### ISSUE THREAD

**Issue by ZhangJiaRed** [bubbliiiing/yolov5-pytorch#115]
Traceback (most recent call last):
  File "D:\anaconda\envs\yolov5-pytorch-bilibili\lib\site-packages\torch\utils\tensorboard\__init__.py", line 2, in <module>
    from tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401
ModuleNotFoundError: No module named 'tensorboard'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/desktop/yolov5-pytorch-bilibili/train.py", line 14, in <module>
    from utils.callbacks import LossHistory
  File "D:\desktop\yolov5-pytorch-bilibili\utils\callbacks.py", line 9, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "D:\anaconda\envs\yolov5-pytorch-bilibili\lib\site-packages\torch\utils\tensorboard\__init__.py", line 4, in <module>
    raise ImportError('TensorBoard logging requires TensorBoard with Python summary writer installed. '
ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above.

进程已结束,退出代码1

导！ 为啥我运行train文件会报这个错，环境用的是你的那个torch=1.2.0。

**Comment by onlywordding** [comment]
我也遇到了，pip install tensorboard就可以了
