### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by staneee** [bubbliiiing/yolov5-pytorch#18]
安装环境后运行存在错误

### 当前本地环境
- windows: **10**
- conda: **4.12.0**
- python:  **Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)] on win32**

#### 安装
```shell
(pytorch-1.2.0) D:\dev\github\yolov5-pytorch>conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```

#### 运行报错
```shell
(pytorch-1.2.0) D:\dev\github\yolov5-pytorch>python train.py
Traceback (most recent call last):
  File "D:\Users\yihan\miniconda3\envs\pytorch-1.2.0\lib\site-packages\torch\utils\tensorboard\__init__.py", line 2, in <module>
    from tensorboard.summary.writer.record_writer import RecordWriter  # noqa F401
ModuleNotFoundError: No module named 'tensorboard'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from utils.callbacks import LossHistory
  File "D:\dev\github\yolov5-pytorch\utils\callbacks.py", line 9, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "D:\Users\yihan\miniconda3\envs\pytorch-1.2.0\lib\site-packages\torch\utils\tensorboard\__init__.py", line 4, in <module>
    raise ImportError('TensorBoard logging requires TensorBoard with Python summary writer installed. '
ImportError: TensorBoard logging requires TensorBoard with Python summary writer installed. This should be available in 1.14 or above.

```

**Comment by staneee** [comment]
按照此教程进行按照：https://blog.csdn.net/weixin_44791964/article/details/106037141

### 创建虚拟环境
```cmd
D:\>conda create -n pytorch python=3.6
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\Users\yihan\miniconda3\envs\pytorch

  added / updated specs:
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.6.2               |                0        31.5 MB  https://mirrors.ustc.edu.cn/anaconda/pkgs/free
    ------------------------------------------------------------
                                           Total:        31.5 MB

The following NEW packages will be INSTALLED:

  certifi            anaconda/pkgs/free/win-64::certifi-2016.2.28-py36_0
  pip                anaconda/pkgs/free/win-64::pip-9.0.1-py36_1
  python             anaconda/pkgs/free/win-64::python-3.6.2-0
  setuptools         anaconda/pkgs/free/win-64::setuptools-36.4.0-py36_1
  vc                 anaconda/pkgs/free/win-64::vc-14-0
  vs2015_runtime     anaconda/pkgs/free/win-64::vs2015_runtime-14.0.25420-0
  wheel              anaconda/pkgs/free/win-64::wheel-0.29.0-py36_0
  wincertstore       anaconda/pkgs/free/win-64::wincertstore-0.2-py36_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
python-3.6.2         | 31.5 MB   | ################################################################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pytorch
#
# To deactivate an active environment, use
#
#     $ conda deactivate


D:\>conda activate pytorch
```
### 安装torch
```cmd
(pytorch) D:\>cd D:\env\pytorch\1.2.0

(pytorch) D:\env\pytorch\1.2.0>pip install torch-1.2.0-cp36-cp36m-win_amd64.whl torchvision-0.4.0-cp36-cp36m-win_amd64.whl
Processing d:\env\pytorch\1.2.0\torch-1.2.0-cp36-cp36m-win_amd64.whl
Processing d:\env\pytorch\1.2.0\torchvision-0.4.0-cp36-cp36m-win_amd64.whl
Collecting numpy (from torch==1.2.0)
  Could not fetch URL http://pypi.mirrors.ustc.edu.cn/simple/numpy/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748) - skipping
  Could not find a version that satisfies the requirement numpy (from torch==1.2.0) (from versions: )
No matching distribution found for numpy (from torch==1.2.0)
You are using pip version 9.0.1, however version 22.0.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by bubbliiiing** [comment]
你装一下tensorboard

**Comment by staneee** [comment]
以及解决，安装环境如下： 
- pytorch 1.8.0
- Python 3.8.5

**Comment by bubbliiiing** [comment]
0 0好的
