### ISSUE TITLE
训练自己的数据集，训练和测试均没问题，但运行get_map.py文件时，报错ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by JackEric6** [bubbliiiing/yolov5-pytorch#32]
up大大，您好，我用自己的数据集训练了您的yolov5网络，数据集只有一个类别drone,训练预测均没问题，最后的get_map 出问题了，运行get_map.py文件后，报错ZeroDivisionError: float division by zero，yolo.py文件的的权重和class文件路径和get_map.py文件的class路径均已更改，请up大大花时间看一下，问题出在哪里？按照报错的信息来看是分母为0，但是n_classes的值没看明白怎么为0 了，还请up大大答疑解惑。
报错信息：
`Load model.
logs/ep096-loss0.001-val_loss0.001.pth model, anchors, and classes loaded.
  0%|          | 0/234 [00:00<?, ?it/s]Load model done.
Get predict result.
100%|██████████| 234/234 [00:15<00:00, 14.96it/s] 100%|██████████| 234/234 [00:00<00:00, 21775.54it/s] Get predict result done.
Get ground truth result.
Get ground truth result done.
Get map.
Traceback (most recent call last):   File "/home/king/Jiang/yolov5-pytorch-bilibili/get_map.py", line 107, in <module>     get_map(MINOVERLAP, True, path = map_out_path)   File "/home/king/Jiang/yolov5-pytorch-bilibili/utils/utils_map.py", line 641, in get_map     mAP     = sum_AP / n_classes ZeroDivisionError: float division by zero `
![E1B49B896FADBBB3A3EF45892ECCAFC5](https://user-images.githubusercontent.com/84906336/169024169-376b6cc2-4902-45f6-8167-f568e3a15764.jpg)
![FB0CBA427E98F19D17B00A5F7C6447A6](https://user-images.githubusercontent.com/84906336/169024223-ef0b3cbb-bf7f-452f-9783-0067e5f229b4.jpg)
![414](https://user-images.githubusercontent.com/84906336/169024585-f441761a-935c-406f-a7ad-b4adabffb654.jpg)

**Comment by bubbliiiing** [comment]
没有预测结果，问题汇总

**Comment by JackEric6** [comment]
> 没有预测结果，问题汇总

看过啦，这应该算是评估结果吧，2007_train.txt文件内含有目标信息，数据集训练1744张图片，验证集436张图片，数据集数量应该是够的，有解冻训练，关于解冻的参数没有调整，还是up大大您的默认值，训练了100epoch，voc_annotation内的class也修改过了，还是一脸疑惑，没有找到问题出在哪里,按理来说，您的yolov5模型应该是可以训练一个类别的吧？
![_JNWZE2H9A{T( `2V1KJ LN](https://user-images.githubusercontent.com/84906336/169262506-b33e80e3-b3f6-4807-beaf-fdf195536277.png)

**Comment by bubbliiiing** [comment]
1、你如何设置trainval_percent为0.1？
2、有目标信息到不了0.001的loss
