### ISSUE TITLE
使用colab训练自己数据集出现了报错

### ISSUE THREAD

**Issue by wrwriven** [bubbliiiing/yolov5-pytorch#35]
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:490: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Start Train
Epoch 1/300:   0% 0/18 [00:00<?, ?it/s<class 'dict'>]Traceback (most recent call last):
  File "train.py", line 543, in <module>
    fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)
  File "/content/drive/MyDrive/Model/yolov5-pytorch/utils/utils_fit.py", line 16, in fit_one_epoch
    for iteration, batch in enumerate(gen):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 457, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/Model/yolov5-pytorch/utils/dataloader.py", line 48, in __getitem__
    image, box  = self.get_random_data(self.annotation_lines[index], self.input_shape, random = self.train)
  File "/content/drive/MyDrive/Model/yolov5-pytorch/utils/dataloader.py", line 77, in get_random_data
    image   = Image.open(line[0])
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Model/yolov5-pytorch/VOCdevkit/VOC2007/JPEGImages/TED9.jpg'

**Comment by wrwriven** [comment]
运行voc设置模式0，是可以的但是训练的时候就不行了

**Comment by bubbliiiing** [comment]
这个路径没有文件
