### ISSUE TITLE
出现下面的报错

### ISSUE THREAD

**Issue by yk20210324** [bubbliiiing/yolov5-pytorch#54]
在运行train.py、predict.py文件时，报错——
Traceback (most recent call last):
  File "G:/yk/yolov5-pytorch-main/predict.py", line 91, in <module>
    r_image = yolo.detect_image(image, crop = crop, count=count)
  File "G:\yk\yolov5-pytorch-main\yolo.py", line 152, in detect_image
    outputs = self.net(images)
  File "G:\anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "G:\anaconda3\envs\py36\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "G:\anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "G:\yk\yolov5-pytorch-main\nets\yolo.py", line 81, in forward
    feat1 = self.conv_1x1_feat1(feat1)
  File "G:\anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'YoloBody' object has no attribute 'conv_1x1_feat1'

**Comment by yk20210324** [comment]
已经解决啦

**Comment by bubbliiiing** [comment]
OK

**Comment by MokeAstor** [comment]
> 已经解决啦

能教一下怎么解决的吗，非常感谢
