### ISSUE TITLE
训练报错 KeyError: 'backbone.dark2.1.m.1.cv1.conv.weight'

### ISSUE THREAD

**Issue by Choikey11** [bubbliiiing/yolov5-pytorch#8]
您好，我用yolov5训练数据集时，出现KeyError: 'backbone.dark2.1.m.1.cv1.conv.weight'这个错误。不知道怎么解决。想麻烦您帮我看看，谢谢！
完整报错：
D:\software\anaconda3\envs\yolov5\python.exe D:/ZYQ/project/yolov5-pytorch-main/train.py
initialize network with normal type
Load weights model_data/yolov5_l.pth.
Traceback (most recent call last):
  File "D:/ZYQ/project/yolov5-pytorch-main/train.py", line 200, in <module>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
  File "D:/ZYQ/project/yolov5-pytorch-main/train.py", line 200, in <dictcomp>
    pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
KeyError: 'backbone.dark2.1.m.1.cv1.conv.weight'

Process finished with exit code 1

**Comment by bubbliiiing** [comment]
backbone和modelpath不对应呢
